# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
 devices([
   "iPhone 8",
   "iPhone 8 Plus",
   "iPhone 11 Pro",
   "iPhone 11 Pro Max",
   "iPad Pro (12.9-inch) (3rd generation)",
   "iPad Pro (9.7-inch)"
 ])

 languages([
   "en-US"
 ])

# The name of the scheme which contains the UI Tests
 scheme("RoutinesUITests")

# Where should the resulting screenshots be stored?
 output_directory("./screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
 clear_previous_screenshots(true)
 skip_open_summary(true)

 workspace("./Routines.xcworkspace")

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
 launch_arguments(["SKIP_ANIMATIONS"])

# For more information about all available options run
# fastlane action snapshot
